image: docker:19.03.6
#image: docker:latest

services:
  # Remeber to set 'privileged = true' into the runner 'config.toml' file (es on hgp5: /srv/gitlab-runner/config/config.toml)
  #- docker:dind
  - docker:19.03.1-dind

stages:
  - build
  - release
  - clean

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  #DOCKER_HOST: tcp://docker:2376
  DOCKER_HOST: tcp://docker:2375
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_CERTDIR: ""
  # https://gitlab.rm.ingv.it/help/user/project/pipelines/settings#git-strategy
  GIT_STRATEGY: clone
  
before_script:
  - export CI_JOB_DATE=$( date +%Y%m%d )
#  - export CONTAINER_TEST_IMAGE="$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  - export CONTAINER_TEST_IMAGE=${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:$CI_COMMIT_REF_SLUG
  - export CONTAINER_RELEASE_IMAGE="$CI_PROJECT_NAME:latest"
  - export CONTAINER_RELEASE_DATE_IMAGE="$CI_PROJECT_NAME:$CI_JOB_DATE"
  - echo $DOCKERHUB_REGISTRY_USER
  - echo $DOCKERHUB_REGISTRY_PSW
  - echo $CI_REGISTRY
#  - echo $CONTAINER_TEST_IMAGE
  - echo $CONTAINER_RELEASE_IMAGE
  - echo $CONTAINER_RELEASE_DATE_IMAGE
#  - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  
build:
  stage: build
  tags:
    - sqlx2-srvr_runner
  script:
    - docker info
    - DOCKER_BUILDKIT=1 docker build --no-cache --pull --tag ${CONTAINER_TEST_IMAGE} .
      #- DOCKER_BUILDKIT=1 docker build --no-cache --pull --tag $CONTAINER_RELEASE_IMAGE .
#    - docker push $CONTAINER_TEST_IMAGE
    #- docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
    
release-image-latest:
  stage: release
  only:
    - master
  tags:
    - sqlx2-srvr_runner
  script:
    - echo ${DOCKERHUB_REGISTRY_PSW} | docker login -u ${DOCKERHUB_REGISTRY_USER} --password-stdin
    - docker push $CONTAINER_TEST_IMAGE && docker image rm $CONTAINER_TEST_IMAGE
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#    - docker push $CONTAINER_RELEASE_IMAGE
    #- docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_DATE_IMAGE
    #- docker push $CONTAINER_RELEASE_DATE_IMAGE
    
#release-image-date:
#  stage: release
#  script:
#    - docker pull $CONTAINER_TEST_IMAGE
#    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_DATE_IMAGE
#    - docker push $CONTAINER_RELEASE_DATE_IMAGE
#  only:
#    - master

#clean_tags:
#  stage: clean
#  tags:
#    - sqlx2-srvr_runner
#  script:
#    - apk add --update curl
#    - "curl --request DELETE --data 'name_regex=latest$' --header 'PRIVATE-TOKEN: t7VGsApTQs2g93gEiysY' 'https://gitlab.rm.ingv.it/api/v4/projects/698/registry/repositories/29/tags' "
    
